# Generated by Django 3.2.11 on 2022-02-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20220221_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablemodel',
            name='use0r',
        ),
        migrations.AddField(
            model_name='tablemodel',
            name='exel',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
